console.log("============== STEP 1 =============");
var myFullName;
console.log("==============Before Initialization=============");
console.log(myFullName);
myFullName="VISHNU BHANGALE";
console.log("==============After Initialization=============");
console.log(myFullName);
var myFullName="VISHNU ARJUN BHANGALE";
console.log("==============After Update Variable=============");
console.log(myFullName);
console.log("=========== STEP 2 ===============");
var myLove="I love only JS";
console.log("My Love:",myLove);

console.log("=========== STEP 3 ===============");
var firstName="VISHNU";
console.log("First Name: ",firstName);
var lastName="BHANGALE";
console.log("Last Name: ",lastName);
var age=30;
console.log("Age: ",age);
var address="Pune";
console.log("Address: ",address);
var pinCode=412105;
console.log("Pincode: ",pinCode);
var gender="Male";
console.log("Gender: ",gender);
var isMarried=true;
console.log("Married/Unmarried: ",isMarried);
